### ISSUE TITLE
More explanation on how this works ?

### ISSUE THREAD

**Issue by seifamou** [benhawley7/fut-search#1]
Hello,

this seems nice project
does it interact with webapp ?
from where we can get the players cvs file ?

**Comment by benhawley7** [comment]
Hi there @seifamou ! 

I built this as a simple little project to learn some Typescript basics.

You basically instantiate the exported class, providing a path to a CSV of FUT data which needs to be in the format specified in the README. With the class loaded and pointed at the CSV, you can then find FUT cards which match particular stats, for example: 

The following snippet would return all of the players in the CSV who are 89 rated strikers in the premier league.
```js
const fut = new FUTSearch("path/to/csv.csv")

fut.listPlayers({
    position: "ST",
    rating: 89,
    league: "Premier League",
})
```

It doesn't interact with a web app - and I don't think this module is a good use case for powering a web API - as every time you make a search, the entire CSV is streamed until a matching player has been found. The correct approach would be to write all the FUT card stats to a database,  such as MongoDB, which can be then be queried by the card stats (I'm currently working on a project for this).

This module is however really convenient for running one-off scripts to filter down the CSV data as you please!

You'll have to source the CSV data by yourself - should be able to find some data on Google.

Hope this helps and let me know if you have more questions.
